site_name: git-rest API
site_description: 'Documentation for the git-rest API.'
theme:
  name: material
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

nav:
  - 'Home': 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'How-To Guides': 'how-to.md'
  - 'API Reference': 'api.md'